In [1]:
# Learning Tensor
import tensorflow as tf
print(tf.__version__)

2.20.0


In [2]:
#create tensors with tf.constant()
scaler=tf.constant(7)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
scaler.ndim

0

In [4]:
vector = tf.constant([1,2])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2])>

In [5]:
vector.ndim

1

In [6]:
matrix=tf.constant([[1,2],[3,4]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [7]:
matrix.shape

TensorShape([2, 2])

In [8]:
matrix.ndim

2

In [9]:
matrix.dtype

tf.int32

In [10]:
another_matrix = tf.constant([[1.,2.],[3.,5.]],dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 5.]], dtype=float16)>

In [11]:
another_matrix.ndim

2

In [12]:
another_matrix.shape

TensorShape([2, 2])

In [13]:
tensor = tf.constant([[[1,2,3]],[[2,3,4]]])
tensor

<tf.Tensor: shape=(2, 1, 3), dtype=int32, numpy=
array([[[1, 2, 3]],

       [[2, 3, 4]]])>

In [14]:
# Creating tensor using tf.Variable()
changeable_tensor = tf.Variable([1,2])
unchangeable_tensor =tf.constant([2,3])
# changeable_tensor,unchangeable_tensor
print(changeable_tensor)



<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2])>


In [15]:
changeable_tensor[0].assign(2)
print(changeable_tensor)

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([2, 2])>


In [16]:
# Creating random tensor
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))
random_1, random_2, random_1==random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [17]:
# Shuffle the order of elements of tensor 
tf.random.set_seed(42)  # global level random seed
not_shuffled= tf.constant([[1,2],
                           [3,4],
                           [5,6]])
tf.random.shuffle(not_shuffled,seed=42)  # Operation level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]])>

In [18]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6],
       [1, 2]])>

In [19]:
# Tensor from Numpy
import numpy as np
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
tf.ones([3,3])

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [21]:
tf.zeros([3,3])

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [22]:
numpy_A = np.arange(1,25,dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [23]:
A = tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])>

In [24]:
rank_4_tensor = tf.zeros(shape=(2,3,4,5))

In [25]:
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [26]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [27]:
print(rank_4_tensor.dtype)
print(rank_4_tensor.ndim)
print(rank_4_tensor.shape)
print(rank_4_tensor.shape[0])
print(rank_4_tensor.shape[-1])
print(tf.size(rank_4_tensor))
print(tf.size(rank_4_tensor).numpy())

<dtype: 'float32'>
4
(2, 3, 4, 5)
2
5
tf.Tensor(120, shape=(), dtype=int32)
120


In [28]:
rank_2_tensor=tf.constant([[2,3],
                           [3,4]])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [3, 4]])>

In [29]:
# rank_3_tensor=rank_2_tensor(...,tf.newaxis)
rank_3_tensor=tf.expand_dims(rank_2_tensor,axis=0)

In [30]:
rank_3_tensor

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[2, 3],
        [3, 4]]])>

In [31]:
# Manipulating tensors(tensor operations)
tensor=tf.constant([[1,2],[2,3]])
tensor+=10

In [32]:
tensor*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[110, 120],
       [120, 130]])>

In [33]:
tensor-=10

In [34]:
tensor+=10

In [35]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [12, 13]])>

In [36]:
tensor-10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [2, 3]])>

In [37]:
tf.add(tensor,20)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[31, 32],
       [32, 33]])>

In [38]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [12, 13]])>

In [39]:
# Dot-product
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[265, 288],
       [288, 313]])>

In [40]:
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[265, 288],
       [288, 313]])>

In [41]:
X=tf.constant([[1,2],[3,4]])
Y=tf.constant([[5,6],[7,8]])
tf.matmul(X,Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[19, 22],
       [43, 50]])>

In [42]:
tf.reshape(Y,shape=(4,1))

<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[5],
       [6],
       [7],
       [8]])>

In [43]:
tf.matmul(tf.reshape(X,shape=(1,4)),tf.reshape(Y,shape=(4,1)))

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[70]])>

In [44]:
tf.transpose(X), tf.transpose(Y)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 3],
        [2, 4]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[5, 7],
        [6, 8]])>)

In [45]:
#  Dot product
tf.tensordot(X,Y,axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[19, 22],
       [43, 50]])>

In [46]:
#  Changing the datatype of tensor
B= tf.constant([1.2])
B.dtype


tf.float32

In [47]:
B=tf.cast(B,dtype=tf.float16)

In [48]:
B.dtype

tf.float16

In [49]:
# Tensor aggregation
tensor1=tf.abs(tensor)
tensor1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [12, 13]])>

In [50]:
tf.reduce_min(tensor1), tf.reduce_max(tensor1),tf.reduce_sum(tensor1)

(<tf.Tensor: shape=(), dtype=int32, numpy=11>,
 <tf.Tensor: shape=(), dtype=int32, numpy=13>,
 <tf.Tensor: shape=(), dtype=int32, numpy=48>)

In [55]:
# import tensorflow_probability as tfp
# tfp.stats.variance(tensor)
print(tf.__version__)


2.20.0


In [59]:
tf.math.reduce_std(tf.cast(tensor,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=0.7071067690849304>

In [62]:
tf.math.reduce_variance(tf.cast(tensor,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=0.5>

In [65]:
tf.random.set_seed(42)
F = tf.random.uniform(shape=[24])
F

<tf.Tensor: shape=(24,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 ], dtype=float32)>

In [66]:
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=15>

In [67]:
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.8996834754943848>

In [68]:
tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463667869567871>

In [70]:
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463667869567871>

In [71]:
# squeezing a tensor
G = tf.constant(tf.random.uniform(shape=[20]),shape=(1,1,1,1,20))

In [72]:
G

<tf.Tensor: shape=(1, 1, 1, 1, 20), dtype=float32, numpy=
array([[[[[0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
           0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
           0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
           0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ]]]]],
      dtype=float32)>

In [73]:
G_squeez=tf.squeeze(G)
G_squeez,G_squeez.shape

(<tf.Tensor: shape=(20,), dtype=float32, numpy=
 array([0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
        0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
        0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
        0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ],
       dtype=float32)>,
 TensorShape([20]))

In [75]:
# one-hot encoding
some_list = [0,1,2,3]
tf.one_hot(some_list,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [78]:
# squaring ,log ,square root
H = tf.range(1,10)
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [79]:
J=tf.constant(np.array([2,3]))
J

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3])>

In [80]:
np.array(J),type(np.array(J))

(array([2, 3]), numpy.ndarray)

In [83]:
tf.config.list_physical_devices('CPU')

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [84]:
!nvidia_smi

'nvidia_smi' is not recognized as an internal or external command,
operable program or batch file.
