In [2]:
# Learning Tensor
import tensorflow as tf
print(tf.__version__)

2.16.1


In [6]:
#create tensors with tf.constant()
scaler=tf.constant(7)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [7]:
scaler.ndim

0

In [8]:
vector = tf.constant([1,2])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2])>

tf.int32

In [11]:
vector.ndim

1

In [12]:
matrix=tf.constant([[1,2],[3,4]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [13]:
matrix.shape

TensorShape([2, 2])

In [14]:
matrix.ndim

2

In [15]:
matrix.dtype

tf.int32

In [17]:
another_matrix = tf.constant([[1.,2.],[3.,5.]],dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 5.]], dtype=float16)>

In [18]:
another_matrix.ndim

2

In [19]:
another_matrix.shape

TensorShape([2, 2])

In [20]:
tensor = tf.constant([[[1,2,3]],[[2,3,4]]])
tensor

<tf.Tensor: shape=(2, 1, 3), dtype=int32, numpy=
array([[[1, 2, 3]],

       [[2, 3, 4]]])>