In [121]:
import tensorflow as tf
print(tf.__version__)

2.20.0


In [122]:
arr=[1,2,3]
ten=tf.constant(arr)
ten

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [123]:
ten[0].shape, ten[0].ndim

(TensorShape([]), 0)

In [124]:
#  Steps in modelling with TensorFlow
# 1. creating a model(tf.keras.Sequential())
# 2. Compiling the model(optimizer,loss,metrics)
# 3. fit the model(epochs)

In [125]:
X=tf.constant([[1,2],[3,4],[4,5],[5,6],[7,8],[8,9],[9,10]])
y=tf.constant([[3],[7],[9],[11],[15],[17],[19]])

In [126]:
tf.random.set_seed(42)
model = tf.keras.Sequential([
    tf.keras.layers.Dense(2),
    tf.keras.layers.Dense(7,activation='relu'),
    tf.keras.layers.Dense(7,activation='relu'),
    tf.keras.layers.Dense(3,activation='relu'),

    tf.keras.layers.Dense(1)
])
model.compile(
    loss=tf.keras.losses.mae,
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
    metrics=['mae']
)
model.fit(X,y,epochs=500)

Epoch 1/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 4s 4s/step - loss: 11.5126 - mae: 11.5126
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - loss: 11.5053 - mae: 11.5053
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - loss: 11.4979 - mae: 11.4979
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - loss: 11.4904 - mae: 11.4904
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - loss: 11.4829 - mae: 11.4829
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 11.4753 - mae: 11.4753
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 11.4675 - mae: 11.4675
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 11.4592 - mae: 11.4592
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 11.4508 - mae: 11.4508
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 11.4422 - mae: 11.4422
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - loss: 11.4335 - mae: 11.4335
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 11.4248 - mae: 11.4248
Epoch 13/500
1/1 ━━━━━━━━━━

In [127]:
pred=tf.constant([[3,4],[4, 5]])
model.predict(pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step


array([[7.0048966],
       [9.006594 ]], dtype=float32)

In [ ]:
#  save the model
model.save('simple_sum.keras')

In [ ]:
# use the save model to predict output
import tensorflow as tf
tens1=tf.constant([[1,2]])
model1 = tf.keras.models.load_model("simple_sum.keras")
model1.predict(tens1)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step


array([[3.001501]], dtype=float32)